#!/bin/bash
set -e

# Worker entrypoint script
# Receives task parameters from environment variables

# Required environment variables
GITLAB_URL="${GITLAB_URL:?Missing GITLAB_URL}"
GITLAB_TOKEN="${GITLAB_TOKEN:?Missing GITLAB_TOKEN}"
PROJECT_ID="${PROJECT_ID:?Missing PROJECT_ID}"
ISSUE_IID="${ISSUE_IID:?Missing ISSUE_IID}"
BRANCH_NAME="${BRANCH_NAME:?Missing BRANCH_NAME}"
USER_PROMPT="${USER_PROMPT:?Missing USER_PROMPT}"

# Optional environment variables
ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL:-http://localhost:11434/v1}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_MODEL="${ANTHROPIC_MODEL:-claude-sonnet-4-20250514}"
TARGET_BRANCH="${TARGET_BRANCH:-main}"

echo "========================================"
echo "GitLab Issue to MR Worker"
echo "========================================"
echo "Project: ${PROJECT_ID}"
echo "Issue: ${ISSUE_IID}"
echo "Branch: ${BRANCH_NAME}"
echo "Target: ${TARGET_BRANCH}"
echo "========================================"

# Extract hostname from GITLAB_URL for git operations
GITLAB_HOST=$(echo "${GITLAB_URL}" | sed 's|https://||' | sed 's|http://||')
GIT_REPO_URL="https://${GITLAB_TOKEN}@${GITLAB_HOST}/project/${PROJECT_ID}.git"

# Clone repository with authentication
echo "Cloning repository..."
git clone "${GIT_REPO_URL}" /workspace
cd /workspace

# Configure git
git config --global user.email "bot@gimr.local"
git config --global user.name "GIMR Bot"

# Checkout/create branch
echo "Checking out branch: ${BRANCH_NAME}"
git fetch origin
if git checkout "${BRANCH_NAME}" 2>/dev/null; then
    echo "Branch already exists, pulling latest..."
    git pull origin "${BRANCH_NAME}"
else
    echo "Creating new branch from ${TARGET_BRANCH}..."
    git checkout -b "${BRANCH_NAME}" "origin/${TARGET_BRANCH}"
fi

# Run Claude CLI with the user prompt
echo "Running Claude CLI..."
echo "Prompt: ${USER_PROMPT}"
echo ""

# Export Anthropic configuration
export ANTHROPIC_BASE_URL
export ANTHROPIC_API_KEY
export ANTHROPIC_MODEL

# Run Claude in agentic mode
# The --dangerously-skip-permissions flag allows Claude to execute code
claude \
    --print \
    --dangerously-skip-permissions \
    "${USER_PROMPT}" > /workspace/result.md 2>&1

RESULT=$?
cat /workspace/result.md

if [ $RESULT -ne 0 ]; then
    echo "Claude CLI failed with exit code: ${RESULT}"
    exit $RESULT
fi

# Check if any changes were made
if git diff --stat | grep -q .; then
    echo "Changes detected, committing..."

    # Add all changes
    git add -A

    # Create commit
    git commit -m "AI: ${USER_PROMPT:0:50}..."

    # Push to remote with authentication
    echo "Pushing to remote..."
    git remote set-url origin "${GIT_REPO_URL}"
    git push -u origin "${BRANCH_NAME}"

    # Get commit SHA
    COMMIT_SHA=$(git rev-parse HEAD)
    echo "Committed: ${COMMIT_SHA}"

    # Create MR via GitLab API
    echo "Creating Merge Request..."

    # Use GitLab API to create MR
    curl -s -X POST "${GITLAB_URL}/api/v4/projects/${PROJECT_ID}/merge_requests" \
        -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{
            \"source_branch\": \"${BRANCH_NAME}\",
            \"target_branch\": \"${TARGET_BRANCH}\",
            \"title\": \"AI: ${USER_PROMPT:0:50}\",
            \"description\": \"Auto-generated by GIMR Bot\\n\\nPrompt: ${USER_PROMPT}\\n\\nCloses #${ISSUE_IID}\",
            \"remove_source_branch\": true
        }" > /workspace/mr_response.json

    MR_WEB_URL=$(cat /workspace/mr_response.json | grep -o '"web_url":"[^"]*"' | cut -d'"' -f4)
    echo "MR created: ${MR_WEB_URL}"

    # Comment on issue with MR link
    echo "Commenting on issue..."
    curl -s -X POST "${GITLAB_URL}/api/v4/projects/${PROJECT_ID}/issues/${ISSUE_IID}/notes" \
        -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{
            \"body\": \"I've created a merge request: ${MR_WEB_URL}\\n\\nPlease review the changes.\"
        }"

    echo "========================================"
    echo "Task completed successfully!"
    echo "========================================"
else
    echo "No changes made by Claude CLI"
    exit 1
fi
